language: ruby

script: xvfb-run bundle exec rspec spec

rvm:
  - 2.5.5
  - 2.6.3

before_script:
  - psql -c 'create database aa_state_machine_test;' -U postgres
  - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
  - RAILS_ENV=test cd spec/dummy && bundle exec rake db:setup
  - cd ../../

